### ISSUE TITLE
Make the readme clearer

### ISSUE THREAD

**Issue by ChristophP** [opvasger/elm-minify#17]
First of all, great tool. It's nice to have something that encapsualtes all the specifics of elm minification. :+1:  However it would be nice if the readme explained more what this package does and why it is more than just running uglify on arbitrary JavaScript. What makes minifying Elm special?

**Comment by opvasger** [comment]
Thanks for the feedback :sunny: I'm going to batch your request with some general work on docs. You can add suggestions and track progress in #18

**Comment by ChristophP** [comment]
Sounds good. Thanks you.
