### ISSUE TITLE
Terser booleans_as_integers config breaks elm/json encoders

### ISSUE THREAD

**Issue by rlefevre** [opvasger/elm-minify#21]
Elm applications minified with `elm-minify` encode json booleans with `elm/json` as:
```
bool: 1
```
instead of the expected:
```
bool: true
```
This is due to elm-minify enabling the `booleans_as_integers` terser option.

This is a very dangerous optimization that can change the format of HTTP requests, generated files, etc. In my case my backend was not accepting `1` instead of `true` and was rejecting the HTTP request with a 422 Bad Format.

I believe that all terser options enabled that are false by default (like this one) should be very carefully reviewed as they are usually false for a good reason.

**Comment by opvasger** [comment]
thank you very much! :sunny: I did quite a lot of testing before enabling this, but didn't catch it initially - Will publish ASAP!

**Comment by opvasger** [comment]
2.0.2 has been published, revertering the `bool` -> `int` transformation.

**Comment by rlefevre** [comment]
Thank you very much for your fast reactivity.
