### ISSUE TITLE
Running twice elm-minify reduces slightly more the file size

### ISSUE THREAD

**Issue by rlefevre** [opvasger/elm-minify#6]
When running twice `elm-minify` on a file, the file size is slightly reduced again the second time, suggesting that elm-minify does not perform all possible optimizations at once.

Example:

    $ ls -la *.js
    -rw-r--r-- 1 dmy dmy 197879 sept. 18 19:54 elm.js
    $ elm-minify elm.js
    $ ls -la *.js
    -rw-r--r-- 1 dmy dmy 197879 sept. 18 19:54 elm.js
    -rw-r--r-- 1 dmy dmy  53982 sept. 18 19:58 elm.min.js
    $ elm-minify elm.min.js
    $ ls -la *.js
    -rw-r--r-- 1 dmy dmy 197879 sept. 18 19:54 elm.js
    -rw-r--r-- 1 dmy dmy  53982 sept. 18 19:58 elm.min.js
    -rw-r--r-- 1 dmy dmy  53870 sept. 18 19:58 elm.min.min.js

**Comment by opvasger** [comment]
That's right! 👍 I've played around with the configuration, running multiple rounds of different settings. I seems to me the most noticable difference was with 2 rounds of compression and then mangling.

but yes, you can configure Uglify to run compression a couple of times. 1 round was what the original script did. 2 rounds is what im doing. 3 rounds is sliiiiightly smaller with 4 rounds doing no difference compared to 3. Time difference between 2 and 3 rounds wasn't completely insignificant, so defaulted on 2.

This is all measured on my MacBook Pro 2015, compiling the very very small example in the repo. I wonder how different configurations with bigger projects would look!

Feel free to fork, experiment and make a pull request if you find something interesting!

**Comment by rlefevre** [comment]
I tried with [elm-spa-example](https://github.com/rtfeldman/elm-spa-example) and the difference between 2. and 3. is around 0.25%, so I agree that 2. looks like a reasonable default choice.

    384660 sept. 18 21:07 elm.js
    107987 sept. 18 21:07 elm.min.js
    107715 sept. 18 21:07 elm.min.min.js
    107715 sept. 18 21:07 elm.min.min.min.js

Maybe an option to add a 3rd round with 2 rounds by default would satisfy everybody?

**Comment by opvasger** [comment]
I'll add a flag for compression-rounds 👍

**Comment by opvasger** [comment]
#7

**Comment by rlefevre** [comment]
IIRC, the first two rounds are not identical (uglify arguments are different), and more than 3 rounds is useless, therefore I'm not sure that a `--rounds` flag is the best. I don't have a better idea for the flag name right now though.

**Comment by opvasger** [comment]
--extra-round?
